import type { Client, KycQueueItem, AuditLogEntry } from "@/types/ankora";
import { dummyP2POrders } from "./dummy-data";

export const dummyClients: Client[] = [
  {
    id: "cli-001",
    name: "Mariano Pfeiffer",
    email: "mpfeiffer@ankora.io",
    country: "Argentina",
    walletShort: "0x7f3a…b21e",
    kycStatus: "verified",
    tier: "calificado",
    joinedAt: "2025-08-14",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 43000,
    portfolioValueUsd: 47370,
    ytdReturnPct: 10.2,
    txCount: 18,
  },
  {
    id: "cli-002",
    name: "Sofía Castellanos",
    email: "sofia.c@protonmail.com",
    country: "Argentina",
    walletShort: "0x8c4a…b21e",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2025-11-03",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 12500,
    portfolioValueUsd: 13420,
    ytdReturnPct: 7.4,
    txCount: 9,
  },
  {
    id: "cli-003",
    name: "Diego Martinelli",
    email: "dmartinelli@mail.com",
    country: "Argentina",
    walletShort: "0x1f88…a3c1",
    kycStatus: "verified",
    tier: "institucional",
    joinedAt: "2025-06-20",
    lastActivityAt: "2026-04-21",
    totalInvestedUsd: 180000,
    portfolioValueUsd: 203100,
    ytdReturnPct: 12.8,
    txCount: 42,
  },
  {
    id: "cli-004",
    name: "Valentina Romero",
    email: "vromero@outlook.com",
    country: "Uruguay",
    walletShort: "0x4b12…9dff",
    kycStatus: "pending",
    tier: "retail",
    joinedAt: "2026-04-15",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 0,
    portfolioValueUsd: 0,
    ytdReturnPct: 0,
    txCount: 0,
  },
  {
    id: "cli-005",
    name: "Andrés Paz",
    email: "apaz@gmail.com",
    country: "Argentina",
    walletShort: "0xaa77…1f3b",
    kycStatus: "verified",
    tier: "calificado",
    joinedAt: "2025-09-12",
    lastActivityAt: "2026-04-20",
    totalInvestedUsd: 68000,
    portfolioValueUsd: 72940,
    ytdReturnPct: 7.3,
    txCount: 24,
  },
  {
    id: "cli-006",
    name: "Florencia Linares",
    email: "flinares@bafa.com.ar",
    country: "Argentina",
    walletShort: "0xef31…a9b2",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2025-10-28",
    lastActivityAt: "2026-04-18",
    totalInvestedUsd: 8500,
    portfolioValueUsd: 9020,
    ytdReturnPct: 6.1,
    txCount: 7,
  },
  {
    id: "cli-007",
    name: "Lucas Benítez",
    email: "lbenitez@live.com",
    country: "Argentina",
    walletShort: "0x9f21…b4e2",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2025-12-05",
    lastActivityAt: "2026-04-19",
    totalInvestedUsd: 4500,
    portfolioValueUsd: 4850,
    ytdReturnPct: 7.8,
    txCount: 5,
  },
  {
    id: "cli-008",
    name: "Camila Russo",
    email: "crusso@defiant.com",
    country: "España",
    walletShort: "0x3c88…f1a4",
    kycStatus: "verified",
    tier: "calificado",
    joinedAt: "2025-07-18",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 35000,
    portfolioValueUsd: 38650,
    ytdReturnPct: 10.4,
    txCount: 19,
  },
  {
    id: "cli-009",
    name: "Tomás Iglesias",
    email: "tiglesias@hotmail.com",
    country: "Argentina",
    walletShort: "0xbd4a…0c11",
    kycStatus: "expired",
    tier: "retail",
    joinedAt: "2024-11-02",
    lastActivityAt: "2026-01-10",
    totalInvestedUsd: 5500,
    portfolioValueUsd: 5830,
    ytdReturnPct: 6.0,
    txCount: 11,
  },
  {
    id: "cli-010",
    name: "Paula Giménez",
    email: "pgimenez@gmail.com",
    country: "Argentina",
    walletShort: "0x7a66…e4b1",
    kycStatus: "pending",
    tier: "retail",
    joinedAt: "2026-04-19",
    lastActivityAt: "2026-04-21",
    totalInvestedUsd: 0,
    portfolioValueUsd: 0,
    ytdReturnPct: 0,
    txCount: 0,
  },
  {
    id: "cli-011",
    name: "Nicolás Rivera",
    email: "nrivera@agro.com.ar",
    country: "Argentina",
    walletShort: "0x02c3…9f70",
    kycStatus: "verified",
    tier: "institucional",
    joinedAt: "2025-05-01",
    lastActivityAt: "2026-04-15",
    totalInvestedUsd: 420000,
    portfolioValueUsd: 476800,
    ytdReturnPct: 13.5,
    txCount: 67,
    pep: true,
  },
  {
    id: "cli-012",
    name: "Agustina Moreno",
    email: "amoreno@icloud.com",
    country: "Argentina",
    walletShort: "0xe111…77dd",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2026-01-22",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 2500,
    portfolioValueUsd: 2640,
    ytdReturnPct: 5.6,
    txCount: 3,
  },
  {
    id: "cli-013",
    name: "Emiliano Corti",
    email: "ecorti@mail.com",
    country: "Chile",
    walletShort: "0x6a2e…33bb",
    kycStatus: "rejected",
    tier: "retail",
    joinedAt: "2026-03-15",
    lastActivityAt: "2026-03-20",
    totalInvestedUsd: 0,
    portfolioValueUsd: 0,
    ytdReturnPct: 0,
    txCount: 0,
    flagged: true,
  },
  {
    id: "cli-014",
    name: "Julieta Vega",
    email: "jvega@gmail.com",
    country: "Argentina",
    walletShort: "0xdd31…7e9f",
    kycStatus: "verified",
    tier: "calificado",
    joinedAt: "2025-08-30",
    lastActivityAt: "2026-04-21",
    totalInvestedUsd: 55000,
    portfolioValueUsd: 60280,
    ytdReturnPct: 9.6,
    txCount: 22,
  },
  {
    id: "cli-015",
    name: "Facundo Álvarez",
    email: "falvarez@trading.com.ar",
    country: "Argentina",
    walletShort: "0x55f1…c2a9",
    kycStatus: "verified",
    tier: "calificado",
    joinedAt: "2025-03-14",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 92000,
    portfolioValueUsd: 104100,
    ytdReturnPct: 13.2,
    txCount: 48,
  },
  {
    id: "cli-016",
    name: "Carolina Ferraro",
    email: "cferraro@ibm.com",
    country: "Argentina",
    walletShort: "0x89bb…12fa",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2025-10-10",
    lastActivityAt: "2026-04-10",
    totalInvestedUsd: 6500,
    portfolioValueUsd: 6970,
    ytdReturnPct: 7.2,
    txCount: 8,
  },
  {
    id: "cli-017",
    name: "Ignacio Sosa",
    email: "isosa@startup.io",
    country: "Argentina",
    walletShort: "0x12c7…a8d2",
    kycStatus: "pending",
    tier: "retail",
    joinedAt: "2026-04-20",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 0,
    portfolioValueUsd: 0,
    ytdReturnPct: 0,
    txCount: 0,
  },
  {
    id: "cli-018",
    name: "Mercedes Otero",
    email: "motero@consultora.com",
    country: "Argentina",
    walletShort: "0x4d2a…e7c3",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2026-02-08",
    lastActivityAt: "2026-04-17",
    totalInvestedUsd: 3200,
    portfolioValueUsd: 3360,
    ytdReturnPct: 5.0,
    txCount: 4,
  },
  {
    id: "cli-019",
    name: "Gonzalo Maciel",
    email: "gmaciel@family.office",
    country: "Uruguay",
    walletShort: "0xfa01…6612",
    kycStatus: "verified",
    tier: "institucional",
    joinedAt: "2024-12-15",
    lastActivityAt: "2026-04-21",
    totalInvestedUsd: 850000,
    portfolioValueUsd: 968200,
    ytdReturnPct: 13.9,
    txCount: 102,
  },
  {
    id: "cli-020",
    name: "Belén Ramírez",
    email: "bramirez@yahoo.com",
    country: "Argentina",
    walletShort: "0xc3e8…5544",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2025-11-20",
    lastActivityAt: "2026-04-16",
    totalInvestedUsd: 7800,
    portfolioValueUsd: 8320,
    ytdReturnPct: 6.7,
    txCount: 10,
  },
  {
    id: "cli-021",
    name: "Rodrigo Falcón",
    email: "rfalcon@mining.co",
    country: "Chile",
    walletShort: "0x88dd…ff01",
    kycStatus: "pending",
    tier: "calificado",
    joinedAt: "2026-04-18",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 0,
    portfolioValueUsd: 0,
    ytdReturnPct: 0,
    txCount: 0,
    flagged: true,
  },
  {
    id: "cli-022",
    name: "Micaela López",
    email: "mlopez@gmail.com",
    country: "Argentina",
    walletShort: "0x1d22…bbcc",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2026-03-01",
    lastActivityAt: "2026-04-19",
    totalInvestedUsd: 1500,
    portfolioValueUsd: 1570,
    ytdReturnPct: 4.7,
    txCount: 2,
  },
  {
    id: "cli-023",
    name: "Joaquín Núñez",
    email: "jnunez@abogados.com.ar",
    country: "Argentina",
    walletShort: "0x55aa…0099",
    kycStatus: "verified",
    tier: "calificado",
    joinedAt: "2025-07-05",
    lastActivityAt: "2026-04-11",
    totalInvestedUsd: 28000,
    portfolioValueUsd: 30520,
    ytdReturnPct: 9.0,
    txCount: 17,
  },
  {
    id: "cli-024",
    name: "Estefanía Torres",
    email: "etorres@hospital.com",
    country: "Argentina",
    walletShort: "0xaa11…bb22",
    kycStatus: "verified",
    tier: "retail",
    joinedAt: "2025-09-08",
    lastActivityAt: "2026-04-19",
    totalInvestedUsd: 4200,
    portfolioValueUsd: 4410,
    ytdReturnPct: 5.0,
    txCount: 6,
  },
  {
    id: "cli-025",
    name: "Santiago Oría",
    email: "soria@techfund.com",
    country: "Argentina",
    walletShort: "0xcc88…dd77",
    kycStatus: "verified",
    tier: "institucional",
    joinedAt: "2025-04-22",
    lastActivityAt: "2026-04-22",
    totalInvestedUsd: 1200000,
    portfolioValueUsd: 1368000,
    ytdReturnPct: 14.0,
    txCount: 156,
  },
];

export function getClientById(id: string): Client | undefined {
  return dummyClients.find((c) => c.id === id);
}

export const dummyKycQueue: KycQueueItem[] = [
  { id: "kyc-01", clientId: "cli-004", clientName: "Valentina Romero", submittedAt: "2026-04-22T09:14:00Z", docsCount: 4, pendingDays: 0, riskScore: "low" },
  { id: "kyc-02", clientId: "cli-010", clientName: "Paula Giménez", submittedAt: "2026-04-21T16:42:00Z", docsCount: 3, pendingDays: 1, riskScore: "low" },
  { id: "kyc-03", clientId: "cli-017", clientName: "Ignacio Sosa", submittedAt: "2026-04-20T11:03:00Z", docsCount: 4, pendingDays: 2, riskScore: "medium" },
  { id: "kyc-04", clientId: "cli-021", clientName: "Rodrigo Falcón", submittedAt: "2026-04-18T14:30:00Z", docsCount: 5, pendingDays: 4, riskScore: "high" },
];

export const dummyAuditLog: AuditLogEntry[] = [
  { id: "a-001", timestamp: "2026-04-22T10:14:00Z", actor: "mpfeiffer@ankora.io", action: "p2p.order.published", target: "P2P-OWN-01", ip: "181.47.22.144" },
  { id: "a-002", timestamp: "2026-04-22T09:47:00Z", actor: "admin@ankora.io", action: "kyc.approved", target: "cli-002", ip: "200.115.103.89" },
  { id: "a-003", timestamp: "2026-04-22T08:20:00Z", actor: "system", action: "dividendo.distributed", target: "cafayate · Q1 2026", ip: "-" },
  { id: "a-004", timestamp: "2026-04-21T18:33:00Z", actor: "admin@ankora.io", action: "project.milestone.completed", target: "cafayate · vendimia 2026", ip: "200.115.103.89" },
  { id: "a-005", timestamp: "2026-04-21T14:11:00Z", actor: "compliance@ankora.io", action: "user.flagged", target: "cli-013", ip: "200.115.103.89" },
  { id: "a-006", timestamp: "2026-04-21T10:08:00Z", actor: "system", action: "p2p.trade.executed", target: "P2P-AX73 · 12 tokens", ip: "-" },
];

// ===== Aggregates =====

export function getPlatformStats() {
  const clients = dummyClients;
  const totalAumUsd = clients.reduce((s, c) => s + c.portfolioValueUsd, 0);
  const totalInvestedUsd = clients.reduce((s, c) => s + c.totalInvestedUsd, 0);
  const activeClients = clients.filter((c) => c.kycStatus === "verified" && c.portfolioValueUsd > 0).length;
  const kycPending = clients.filter((c) => c.kycStatus === "pending").length;
  const kycExpired = clients.filter((c) => c.kycStatus === "expired").length;
  const flagged = clients.filter((c) => c.flagged || c.pep).length;
  const totalTxs = clients.reduce((s, c) => s + c.txCount, 0);
  const p2pVolume24h = dummyP2POrders.reduce(
    (s, o) => s + o.tokensFilled * o.pricePerToken,
    0
  );
  const p2pOpenOrders = dummyP2POrders.filter(
    (o) => o.status === "open" || o.status === "partial"
  ).length;
  return {
    totalAumUsd,
    totalInvestedUsd,
    platformReturnPct: ((totalAumUsd - totalInvestedUsd) / totalInvestedUsd) * 100,
    activeClients,
    totalClients: clients.length,
    kycPending,
    kycExpired,
    flagged,
    totalTxs,
    p2pVolume24h,
    p2pOpenOrders,
    // Dummy: fees collected estimation
    feesCollectedMonthUsd: 8420,
    dividendsToDistributeUsd: 12850,
  };
}

export function formatUsdShort(value: number): string {
  if (value >= 1_000_000) return `$${(value / 1_000_000).toFixed(2)}M`;
  if (value >= 1_000) return `$${(value / 1_000).toFixed(1)}K`;
  return `$${value.toFixed(0)}`;
}
